### Part1
1. At line 9, the code prints: values added:  20
2. At line 13, the code prints: final result:  20
3. At line 9, the code prints: values added:  20
4. At line 13, the code returns an error because the `let` declaration only declares the variable in the given block scope and the line 13 'console.log' is outside that block.
5. At line 9, the code returns an error because the `const` declaration prevents `result` from being reassigned in line 7 and therefore the program crashes
6. Since the code crashes at line 7, the code at line 13 is never ran and therefore nothing is printed.
